## This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish python package to TestPyPI

on:
   release:
     types: [prereleased]
   push:
     branches: [test_release]

jobs:
  bdist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build manylinux wheel
      uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux_2_28_x86_64
      with:
        build-requirements: 'numpy Cython'
        system-packages: 'tbb-devel'
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311'
    - name: Remove linux_x86_64 wheels
      run: |
        sudo find . -type f -iname "*-linux_x86_64.whl" -delete
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_API_KEY }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true

  sdist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        sudo apt-get -y install libtbb-dev
        python -m pip install --upgrade pip
        pip install build Cython
    - name: Build package
      run: python -m build
    - name: Remove linux_x86_64 wheels
      run: |
        sudo find . -type f -iname "*-linux_x86_64.whl" -delete
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.TESTPYPI_API_KEY }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
